-- Initial schema for orders query database
-- This creates the read model table for CQRS architecture

CREATE TABLE IF NOT EXISTS orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id VARCHAR(36) NOT NULL,
    customer_id  BIGINT         NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status       VARCHAR(20)    NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index on customer_id for efficient queries
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders (customer_id);

-- Create index on status for efficient filtering
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);

-- Create index on created_at for time-based queries
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
