-- Create inbox table for idempotent message processing with support for out-of-order event handling
-- This ensures that duplicate messages are not processed multiple times and handles race conditions

CREATE TABLE IF NOT EXISTS inbox_events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id              BIGINT       NOT NULL,
    message_id            VARCHAR(255), -- RabbitMQ message ID if available
    event_type            VARCHAR(100) NOT NULL,
    processing_status     VARCHAR(20)  NOT NULL DEFAULT 'PROCESSED',
    target_entity_id      VARCHAR(100), -- The ID of the entity this event targets (for dependency tracking)
    depends_on_event_type VARCHAR(100), -- What event type this event depends on
    processed_at          TIMESTAMP,    -- When the event was successfully processed (null for deferred/failed)
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_message         VARCHAR(500), -- Error message for failed events
    event_payload         TEXT,         -- Store the original event payload for reprocessing
    CONSTRAINT uk_inbox_event_id UNIQUE (event_id)
);

-- Create index on event_id for fast lookups during idempotency checks
CREATE INDEX IF NOT EXISTS idx_inbox_events_event_id ON inbox_events (event_id);

-- Create index on processing_status for efficient queries of deferred events
CREATE INDEX IF NOT EXISTS idx_inbox_events_processing_status ON inbox_events (processing_status);

-- Create index on target_entity_id for dependency lookup
CREATE INDEX IF NOT EXISTS idx_inbox_events_target_entity_id ON inbox_events (target_entity_id);

-- Create index on depends_on_event_type for dependency resolution
CREATE INDEX IF NOT EXISTS idx_inbox_events_depends_on_event_type ON inbox_events (depends_on_event_type);

-- Create index on processed_at for cleanup operations
CREATE INDEX IF NOT EXISTS idx_inbox_events_processed_at ON inbox_events (processed_at);

-- Create index on created_at for cleanup operations
CREATE INDEX IF NOT EXISTS idx_inbox_events_created_at ON inbox_events (created_at);

-- Create index on event_type for monitoring and analytics
CREATE INDEX IF NOT EXISTS idx_inbox_events_event_type ON inbox_events (event_type);
