server:
  port: 8081

spring:
  application:
    name: order-query-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_query
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5
        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2

app:
  messaging:
    exchange: orders.exchange
    queue: orders.query.queue
    routing-key: order.created

logging:
  level:
    dev.denissajnar.query: DEBUG
    org.springframework.amqp: INFO
    org.hibernate.SQL: INFO
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
